# This workflow performs static analysis checks.
name: static analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  not-grep:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python and install setuptools
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install setuptools dependency
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
      - name: not-grep
        uses: mattsb42-meta/not-grep@1.0.0
